### ISSUE TITLE
New Story: Allow adjustment of 'Creativity'

### ISSUE THREAD

**Issue by mattlindsey** [mattlindsey/mythographer#10]
Allow the user to adust the 'creativity' level by something like a slider from Low to High or a choice of options such as Conservative, Balanced, or Inventive.  Then pass a parameter like 'temperature' to the LLM to influence the creativity.

**Comment by mattlindsey** [comment]
Hi @acelanoit!  Will you be working on this one?  Let me know if you need anything.
The other contributor (Basil) and I will be chatting tomorrow(December 1) on google meet at 9am ET if you're interested.

**Comment by acelanoit** [comment]
> Hi @acelanoit! Will you be working on this one? Let me know if you need anything. The other contributor (Basil) and I will be chatting tomorrow(December 1) on google meet at 9am ET if you're interested.

Hey @mattlindsey, yes, I'll take care of this (:
