### ISSUE TITLE
Add another/other LLMs

### ISSUE THREAD

**Issue by mattlindsey** [mattlindsey/mythographer#3]
Add support for other LLMs, which should be easy with the langchainrb gem.  Preferably something with a free API so development can be done without any cost.  
Could have a dropdown at top of 'New Story' to select the desired LLM.

Choices are: https://github.com/andreibondarev/langchainrb#supported-llms-and-features

An easy one to add would be Google: https://makersuite.google.com/app/apikey

**Comment by BasilMawejje** [comment]
@mattlindsey I'll work on this.
