### ISSUE TITLE
New Story: Display mythology names instead of ids

### ISSUE THREAD

**Issue by mattlindsey** [mattlindsey/mythographer#8]
In the dropdown on the 'New Story' page, display the mythology names (including 'Unspecified') in the dropdown instead of the id numbers.

It would probably be nice to install and use the 'simple forms' gem:
https://github.com/heartcombo/simple_form

**Comment by acelanoit** [comment]
Hello mattlindsey, I would like to give this a try, would it be ok if I did? Could you please assign the issue to me?

**Comment by mattlindsey** [comment]
Hi @acelanoit. That's great. Let me know if you have any questions.  If you want to chat on our Slack, you can sign up at https://www.agileventures.org and you should get an email with the link.  Let me know if you don't get the email.
